In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation
one_hot_rep = [one_hot(word, voc_size) for word in sent]
one_hot_rep

[[4174, 4744, 5438, 7107],
 [4174, 4744, 5438, 1234],
 [4174, 101, 5438, 4734],
 [9008, 781, 849, 1222, 4458],
 [9008, 781, 849, 1222, 8640],
 [2919, 4174, 145, 5438, 6353],
 [6506, 3093, 2631, 1222]]

In [9]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [10]:
sent_length=8
embedded_docs = pad_sequences(one_hot_rep, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4174 4744 5438 7107]
 [   0    0    0    0 4174 4744 5438 1234]
 [   0    0    0    0 4174  101 5438 4734]
 [   0    0    0 9008  781  849 1222 4458]
 [   0    0    0 9008  781  849 1222 8640]
 [   0    0    0 2919 4174  145 5438 6353]
 [   0    0    0    0 6506 3093 2631 1222]]


In [11]:
## feature representation
dim=10

In [17]:
# Voc_size = How many vocabulary will be in the whole document
# dim = how many dimension it should have like man, woman, royal, fruit, vegetable, vehicle etc.
# sent_length = how many words in a sentence
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/Users/gopalakrishnanm/Documents/Programming/Machine Learning Projects/Krish Naik Udemy/RNN-SentimentAnalysis/RNNSentiProject/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [18]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step


array([[[-0.01606477,  0.01148323,  0.02887284,  0.04973066,
          0.04580345,  0.03381426,  0.04225   ,  0.00347428,
         -0.03700411, -0.04037591],
        [-0.01606477,  0.01148323,  0.02887284,  0.04973066,
          0.04580345,  0.03381426,  0.04225   ,  0.00347428,
         -0.03700411, -0.04037591],
        [-0.01606477,  0.01148323,  0.02887284,  0.04973066,
          0.04580345,  0.03381426,  0.04225   ,  0.00347428,
         -0.03700411, -0.04037591],
        [-0.01606477,  0.01148323,  0.02887284,  0.04973066,
          0.04580345,  0.03381426,  0.04225   ,  0.00347428,
         -0.03700411, -0.04037591],
        [ 0.01337508,  0.02440569,  0.01737997,  0.00436419,
          0.02981614,  0.00417973,  0.00187777, -0.00288241,
         -0.02799471,  0.00254139],
        [ 0.04603784, -0.02792579,  0.01774415,  0.01421449,
         -0.00488709, -0.04396566, -0.04961871, -0.0298704 ,
         -0.0485108 ,  0.00022031],
        [-0.03682465,  0.0276728 ,  0.04443845, -0.0

In [29]:
embedded_docs[0]

array([   0,    0,    0,    0, 4174, 4744, 5438, 7107], dtype=int32)

In [30]:
input_data = embedded_docs[0].reshape(1,-1)

In [31]:
model.predict(input_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step


array([[[-0.01606477,  0.01148323,  0.02887284,  0.04973066,
          0.04580345,  0.03381426,  0.04225   ,  0.00347428,
         -0.03700411, -0.04037591],
        [-0.01606477,  0.01148323,  0.02887284,  0.04973066,
          0.04580345,  0.03381426,  0.04225   ,  0.00347428,
         -0.03700411, -0.04037591],
        [-0.01606477,  0.01148323,  0.02887284,  0.04973066,
          0.04580345,  0.03381426,  0.04225   ,  0.00347428,
         -0.03700411, -0.04037591],
        [-0.01606477,  0.01148323,  0.02887284,  0.04973066,
          0.04580345,  0.03381426,  0.04225   ,  0.00347428,
         -0.03700411, -0.04037591],
        [ 0.01337508,  0.02440569,  0.01737997,  0.00436419,
          0.02981614,  0.00417973,  0.00187777, -0.00288241,
         -0.02799471,  0.00254139],
        [ 0.04603784, -0.02792579,  0.01774415,  0.01421449,
         -0.00488709, -0.04396566, -0.04961871, -0.0298704 ,
         -0.0485108 ,  0.00022031],
        [-0.03682465,  0.0276728 ,  0.04443845, -0.0